---

- name: Configure system
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Ensure timezone is set
      community.general.timezone:
        name: "{{ timezone }}"
        hwclock: local


    - name: Ensure hostname is set
      ansible.builtin.lineinfile:
        path: /etc/hostname
        regexp: "^"
        line: "{{ hostname }}"


    - name: Ensure hosts file is set
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^127.0.0.1"
        line: "127.0.0.1 {{ hostname }}"


    - name: Generate locale
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ locale_list }}"
